# This Dockerfile is used to run the app on Elastic Beanstalk. 
# It works off the published app, so it only needs to run the app (no build step). (to run it, you might need to rename it Dockerfile)
# syntax=docker/dockerfile:1

################################################################################

# Learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md

# First stage named "final": Running the app 
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

# Copy the published output needed to run the app from the build context.
COPY . /app
WORKDIR /app
# Switch to a non-privileged user (defined in the base image) that the app will run under.
# See https://docs.docker.com/go/dockerfile-user-best-practices/
# and https://github.com/dotnet/dotnet-docker/discussions/4764
USER $APP_UID

ENTRYPOINT ["dotnet", "SimpleApiDockerized.dll"]
